# Generated by Django 4.1 on 2022-09-06 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBuiltTaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantName', models.CharField(max_length=55)),
                ('address', models.CharField(max_length=55)),
                ('zipCode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=7)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('stateName', models.CharField(max_length=2)),
                ('cityName', models.CharField(max_length=55)),
                ('cuisineType', models.CharField(max_length=55)),
                ('hoursInterval', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Shell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='TacoTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myBuiltTacoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taco2goapi.mybuilttaco')),
                ('toppingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taco2goapi.topping')),
            ],
        ),
        migrations.CreateModel(
            name='TacoSauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myBuiltTacoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taco2goapi.mybuilttaco')),
                ('sauceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taco2goapi.sauce')),
            ],
        ),
        migrations.CreateModel(
            name='TacoLover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePic', models.URLField()),
                ('userCity', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('userState', models.CharField(max_length=2)),
                ('taco_lover', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyNextUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myFaved', models.BooleanField()),
                ('restaurantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taco2goapi.restaurant')),
                ('tacoLoverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taco2goapi.tacolover')),
            ],
        ),
        migrations.CreateModel(
            name='MyFavs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taco2goapi.rating')),
                ('restaurantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taco2goapi.restaurant')),
                ('tacoLoverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taco2goapi.tacolover')),
            ],
        ),
        migrations.AddField(
            model_name='mybuilttaco',
            name='tacoLoverId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taco2goapi.tacolover'),
        ),
        migrations.AddField(
            model_name='mybuilttaco',
            name='tacoProteinId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taco2goapi.protein'),
        ),
        migrations.AddField(
            model_name='mybuilttaco',
            name='tacoShellId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taco2goapi.shell'),
        ),
    ]
