# Generated by Django 4.1 on 2022-09-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taco2goapi', '0002_rename_taco_lover_tacolover_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybuilttaco',
            name='name',
            field=models.CharField(default='', max_length=55),
        ),
    ]
