# Generated by Django 4.1 on 2022-10-15 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taco2goapi', '0003_mybuilttaco_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacosauce',
            name='myBuiltTacoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taco_sauces', to='taco2goapi.mybuilttaco'),
        ),
        migrations.AlterField(
            model_name='tacosauce',
            name='sauceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taco_sauces', to='taco2goapi.sauce'),
        ),
        migrations.AlterField(
            model_name='tacotopping',
            name='myBuiltTacoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taco_toppings', to='taco2goapi.mybuilttaco'),
        ),
        migrations.AlterField(
            model_name='tacotopping',
            name='toppingId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taco_toppings', to='taco2goapi.topping'),
        ),
    ]
